### ISSUE TITLE
Possibility to override "thirdPartyEmailPasswordDivider" style

### ISSUE THREAD

**Issue by nik2208** [supertokens/supertokens-auth-react#785]
in italian the translation for the english work "or" is "oppure", which is quite long and breaks the flex boundaries of the divider row.
I've searched inside the library but the divider doesn't seem to be customizable.
![Screenshot 2024-01-15 at 09 09 27](https://github.com/supertokens/supertokens-auth-react/assets/28157038/308cf675-7b55-47de-bc8b-b0bd002c2c8c)
is it possible to add it to the set of customisable components?

**Comment by rishabhpoddar** [comment]
I think the component you want to override is `ThirdPartyEmailPasswordHeader_Override`, and then you can add your own react component there instead of ours.

**Comment by nik2208** [comment]
shouldnt I be able to override its style with something like this?

```css
style: `
                [data-supertokens~=container] {
                    --palette-background: 51, 51, 51;
                    --palette-inputBackground: 41, 41, 41;
                    --palette-inputBorder: 41, 41, 41;
                    --palette-textTitle: 255, 255, 255;
                    --palette-textLabel: 255, 255, 255;
                    --palette-textPrimary: 255, 255, 255;
                    --palette-error: 173, 46, 46;
                    --palette-textInput: 169, 169, 169;
                    --palette-textLink: 169, 169, 169;
                    --palette-primary: ${environment.SUPERTOKENS.STYLE.PALETTE_PRIMARY};
                    --palette-primaryBorder: ${environment.SUPERTOKENS.STYLE.PALETTE_PRIMARY_BORDER};
                },
                [data-supertokens~=thirdPartyEmailPasswordDividerOr] {
                    margin-top: 0.55em;
                },
                [data-supertokens~=divider] {
                    flex: 2 3;
                },
            `,
```
